server:
  port: 8083
  host: "localhost"
  context-path: "/payments-ms-01"
  goEnv: "local"

database:
  mysql:
    name: "payments_ms_01"
    host: "localhost"
    port: 3306
    user: "root"
    password: "123456"
    maxOpenConns: 100
    maxIdleConns: 20
    connMaxLifetime: 4h
    connMaxIdleTime: 30m

golang-migrate:
  mysql:
    enabled: true
    locations: migrations/mysql

data:
  redis:
    host: "localhost"
    port: "6379"
    password: ""
    db: 1
    pool-size: 10

jwt:
  secret:
    key: "704abeeb8729b64730f948a4446d35868a22088d347d14da7c7002403e08"

mercadopago:
  access_token: APP_USR-708228168073386-041123-0b0a6f0f72be53912b081fd458c22c40-3330160398
  webhook_secret: "a325f8d5bfc403ad1e12133d0b74c54623f52fa6a7553c81d331b8f1c5dbdd83"
  base_url: "https://api.mercadopago.com"
  notification_url: "https://7cfb-45-161-118-108.ngrok-free.app/payments-ms-01/api/payments/webhook"
  # back_url base para Checkout Pro — el usecase agrega el sufijo /?payment=success|pending|failure
  back_url: "https://4b45-45-161-118-110.ngrok-free.app/app/es/home"

payment-trasnfer:
  cbu/cvu: "1234567890"
  alias: "test.mp"
  

rabbitmq:
  host: "localhost"
  port: "5672"
  username: "guest"
  password: "guest"
  ssl:
    enabled: false
